### ISSUE TITLE
Multiple shadow roots deprecated

### ISSUE THREAD

**Issue by timothyha** [laat/chess-board#7]
Hi, I am trying to use chess-board component in an ionic app it fails with the following error message:

> Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details. (chess-board.js:15)

I am loading chess-board.html via index.html of the ionic app and type <chess-board>FEN</chess-board> in a page's .html

Is there a way to overcome this issue?  Thanks.

**Comment by timothyha** [comment]
It fails here
```
      this._frameRoot = this.createShadowRoot();
      this._frameRoot.appendChild(_templates.frameTemplate.content.cloneNode(true));
```

**Comment by laat** [comment]
It's just a deprecation warning, and it should still work perfectly for a while until Google removes the message. However, I will make the proper changes to my code soon to remove that warning.

**Comment by laat** [comment]
The latest release should be OK now.

**Comment by timothyha** [comment]
Thank you!
